/*=============================================================================
This file was generated by the VimbaClassGenerator
=============================================================================*/


#ifndef MAKOCAM_H
#define MAKOCAM_H

#include "VimbaCPP/Include/VimbaCPP.h"

class MakoCam : public AVT::VmbAPI::Camera
{
    public:
        typedef SP_DECL( MakoCam ) Ptr;

        typedef enum _AcquisitionFrameRateModeEnum
        {
            AcquisitionFrameRateMode_Off = 0,
            AcquisitionFrameRateMode_Basic = 1
        } AcquisitionFrameRateModeEnum;

        typedef enum _AcquisitionModeEnum
        {
            AcquisitionMode_SingleFrame = 0,
            AcquisitionMode_MultiFrame = 1,
            AcquisitionMode_Continuous = 2
        } AcquisitionModeEnum;

        typedef enum _AcquisitionStatusSelectorEnum
        {
            AcquisitionStatusSelector_AcquisitionTriggerWait = 0,
            AcquisitionStatusSelector_AcquisitionActive = 1,
            AcquisitionStatusSelector_AcquisitionTransfer = 2,
            AcquisitionStatusSelector_FrameTriggerWait = 3,
            AcquisitionStatusSelector_FrameActive = 4,
            AcquisitionStatusSelector_ExposureActive = 5
        } AcquisitionStatusSelectorEnum;

        typedef enum _BlackLevelSelectorEnum
        {
            BlackLevelSelector_All = 0
        } BlackLevelSelectorEnum;

        typedef enum _CorrectionModeEnum
        {
            CorrectionMode_Off = 0,
            CorrectionMode_On = 1
        } CorrectionModeEnum;

        typedef enum _CorrectionSelectorEnum
        {
            CorrectionSelector_DefectPixelCorrection = 0,
            CorrectionSelector_FixedPatternNoiseCorrection = 1
        } CorrectionSelectorEnum;

        typedef enum _CorrectionSetDefaultEnum
        {
            CorrectionSetDefault_Factory = 0,
            CorrectionSetDefault_User = 1
        } CorrectionSetDefaultEnum;

        typedef enum _CorrectionSetSelectorEnum
        {
            CorrectionSetSelector_Factory = 0,
            CorrectionSetSelector_User = 1
        } CorrectionSetSelectorEnum;

        typedef enum _DeviceFirmwareIDSelectorEnum
        {
            DeviceFirmwareIDSelector_Current = 0,
            DeviceFirmwareIDSelector_Supported = 1
        } DeviceFirmwareIDSelectorEnum;

        typedef enum _DeviceFirmwareVersionSelectorEnum
        {
            DeviceFirmwareVersionSelector_Current = 0,
            DeviceFirmwareVersionSelector_Programmed = 1
        } DeviceFirmwareVersionSelectorEnum;

        typedef enum _DeviceIndicatorModeEnum
        {
            DeviceIndicatorMode_Inactive = 0,
            DeviceIndicatorMode_Active = 1,
            DeviceIndicatorMode_ErrorStatus = 2
        } DeviceIndicatorModeEnum;

        typedef enum _DeviceLinkThroughputLimitModeEnum
        {
            DeviceLinkThroughputLimitMode_Off = 0,
            DeviceLinkThroughputLimitMode_On = 1
        } DeviceLinkThroughputLimitModeEnum;

        typedef enum _DeviceScanTypeEnum
        {
            DeviceScanType_Areascan = 0
        } DeviceScanTypeEnum;

        typedef enum _DeviceTemperatureSelectorEnum
        {
            DeviceTemperatureSelector_Mainboard = 1
        } DeviceTemperatureSelectorEnum;

        typedef enum _ExposureModeEnum
        {
            ExposureMode_Timed = 1,
            ExposureMode_TriggerWidth = 2
        } ExposureModeEnum;

        typedef enum _FileOpenModeEnum
        {
            FileOpenMode_Read = 1,
            FileOpenMode_Write = 2
        } FileOpenModeEnum;

        typedef enum _FileOperationSelectorEnum
        {
            FileOperationSelector_Open = 0,
            FileOperationSelector_Close = 1,
            FileOperationSelector_Read = 2,
            FileOperationSelector_Write = 3,
            FileOperationSelector_Delete = 4
        } FileOperationSelectorEnum;

        typedef enum _FileOperationStatusEnum
        {
            FileOperationStatus_Success = 0,
            FileOperationStatus_Failure = 1,
            FileOperationStatus_Invalid = 3,
            FileOperationStatus_Denied = 4,
            FileOperationStatus_Error = 5,
            FileOperationStatus_Fault1 = 6,
            FileOperationStatus_Fault2 = 7
        } FileOperationStatusEnum;

        typedef enum _FileProcessStatusEnum
        {
            FileProcessStatus_None = 0,
            FileProcessStatus_UpdateNotRequired = 1
        } FileProcessStatusEnum;

        typedef enum _FileSelectorEnum
        {
            FileSelector_Firmware = 1,
            FileSelector_UserData = 17,
            FileSelector_DefectPixelCorrection = 32,
            FileSelector_FixedPatternNoiseCorrection = 36
        } FileSelectorEnum;

        typedef enum _FileStatusEnum
        {
            FileStatus_Closed = 0,
            FileStatus_Open = 1
        } FileStatusEnum;

        typedef enum _GainSelectorEnum
        {
            GainSelector_All = 0
        } GainSelectorEnum;

        typedef enum _InputDebounceModeEnum
        {
            InputDebounceMode_Off = 0,
            InputDebounceMode_On = 1
        } InputDebounceModeEnum;

        typedef enum _LineModeEnum
        {
            LineMode_Input = 0,
            LineMode_Output = 1
        } LineModeEnum;

        typedef enum _LineSelectorEnum
        {
            LineSelector_Line0 = 0,
            LineSelector_Line1 = 1,
            LineSelector_Line2 = 2,
            LineSelector_Line3 = 3
        } LineSelectorEnum;

        typedef enum _LineSourceEnum
        {
            LineSource_Off = 0,
            LineSource_AcquisitionActive = 1,
            LineSource_FrameTriggerWait = 2,
            LineSource_FrameActive = 3,
            LineSource_ExposureActive = 4,
            LineSource_Stream0TransferActive = 5,
            LineSource_ReadoutActive = 21,
            LineSource_AcquisitionTriggerWait = 22,
            LineSource_BurstTriggerWait = 23,
            LineSource_UserOutput0 = 64,
            LineSource_UserOutput1 = 65,
            LineSource_UserOutput2 = 66,
            LineSource_UserOutput3 = 67
        } LineSourceEnum;

        typedef enum _OutputDurationModeEnum
        {
            OutputDurationMode_Off = 0,
            OutputDurationMode_On = 1
        } OutputDurationModeEnum;

        typedef enum _PixelFormatEnum
        {
            PixelFormat_Mono8 = 17301505,
            PixelFormat_Mono10p = 17432646
        } PixelFormatEnum;

        typedef enum _PixelSizeEnum
        {
            PixelSize_Bpp1 = 1,
            PixelSize_Bpp2 = 2,
            PixelSize_Bpp4 = 4,
            PixelSize_Bpp8 = 8,
            PixelSize_Bpp10 = 10,
            PixelSize_Bpp12 = 12,
            PixelSize_Bpp14 = 14,
            PixelSize_Bpp16 = 16,
            PixelSize_Bpp20 = 20,
            PixelSize_Bpp24 = 24
        } PixelSizeEnum;

        typedef enum _StreamBufferHandlingModeEnum
        {
            StreamBufferHandlingMode_Default = 0
        } StreamBufferHandlingModeEnum;

        typedef enum _StreamTypeEnum
        {
            StreamType_USB3 = 8
        } StreamTypeEnum;

        typedef enum _TriggerActivationEnum
        {
            TriggerActivation_RisingEdge = 0,
            TriggerActivation_FallingEdge = 1,
            TriggerActivation_AnyEdge = 2,
            TriggerActivation_LevelHigh = 3,
            TriggerActivation_LevelLow = 4
        } TriggerActivationEnum;

        typedef enum _TriggerModeEnum
        {
            TriggerMode_Off = 0,
            TriggerMode_On = 1
        } TriggerModeEnum;

        typedef enum _TriggerSelectorEnum
        {
            TriggerSelector_FrameStart = 0,
            TriggerSelector_AcquisitionStart = 1
        } TriggerSelectorEnum;

        typedef enum _TriggerSourceEnum
        {
            TriggerSource_Software = 0,
            TriggerSource_Line0 = 16,
            TriggerSource_Line1 = 17,
            TriggerSource_Line2 = 18,
            TriggerSource_Line3 = 19
        } TriggerSourceEnum;

        typedef enum _UserOutputSelectorEnum
        {
            UserOutputSelector_UserOutput0 = 0,
            UserOutputSelector_UserOutput1 = 1,
            UserOutputSelector_UserOutput2 = 2,
            UserOutputSelector_UserOutput3 = 3
        } UserOutputSelectorEnum;

        typedef enum _UserSetDefaultEnum
        {
            UserSetDefault_Default = 1,
            UserSetDefault_UserSet1 = 2,
            UserSetDefault_UserSet2 = 3,
            UserSetDefault_UserSet3 = 4,
            UserSetDefault_UserSet4 = 5
        } UserSetDefaultEnum;

        typedef enum _UserSetSelectorEnum
        {
            UserSetSelector_Default = 1,
            UserSetSelector_UserSet1 = 2,
            UserSetSelector_UserSet2 = 3,
            UserSetSelector_UserSet3 = 4,
            UserSetSelector_UserSet4 = 5
        } UserSetSelectorEnum;

        
        MakoCam (
            const char         *pCameraID,
            const char         *pCameraName,
            const char         *pCameraModel,
            const char         *pCameraSerialNumber,
            const char         *pInterfaceID,
            VmbInterfaceType    interfaceType,
            const char         *pInterfaceName,
            const char         *pInterfaceSerialNumber,
            VmbAccessModeType   interfacePermittedAccess );


        // Category /AcquisitionControl
        VmbErrorType AcquisitionAbort ();
        VmbErrorType GetAcquisitionAbortFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetAcquisitionFrameCount (VmbInt64_t & value);
        VmbErrorType GetAcquisitionFrameCountFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetAcquisitionFrameRate (double & value);
        VmbErrorType GetAcquisitionFrameRateFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetAcquisitionFrameRateMode (AcquisitionFrameRateModeEnum & value);
        VmbErrorType SetAcquisitionFrameRateMode (AcquisitionFrameRateModeEnum value);
        VmbErrorType GetAcquisitionFrameRateModeFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetAcquisitionMode (AcquisitionModeEnum & value);
        VmbErrorType SetAcquisitionMode (AcquisitionModeEnum value);
        VmbErrorType GetAcquisitionModeFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType AcquisitionStart ();
        VmbErrorType GetAcquisitionStartFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetAcquisitionStatus (bool & value);
        VmbErrorType GetAcquisitionStatusFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetAcquisitionStatusSelector (AcquisitionStatusSelectorEnum & value);
        VmbErrorType SetAcquisitionStatusSelector (AcquisitionStatusSelectorEnum value);
        VmbErrorType GetAcquisitionStatusSelectorFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType AcquisitionStop ();
        VmbErrorType GetAcquisitionStopFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetExposureMode (ExposureModeEnum & value);
        VmbErrorType SetExposureMode (ExposureModeEnum value);
        VmbErrorType GetExposureModeFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetExposureTime (double & value);
        VmbErrorType SetExposureTime (double value);
        VmbErrorType GetExposureTimeFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetTriggerActivation (TriggerActivationEnum & value);
        VmbErrorType SetTriggerActivation (TriggerActivationEnum value);
        VmbErrorType GetTriggerActivationFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetTriggerDelay (double & value);
        VmbErrorType SetTriggerDelay (double value);
        VmbErrorType GetTriggerDelayFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetTriggerMode (TriggerModeEnum & value);
        VmbErrorType SetTriggerMode (TriggerModeEnum value);
        VmbErrorType GetTriggerModeFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetTriggerSelector (TriggerSelectorEnum & value);
        VmbErrorType SetTriggerSelector (TriggerSelectorEnum value);
        VmbErrorType GetTriggerSelectorFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType TriggerSoftware ();
        VmbErrorType GetTriggerSoftwareFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetTriggerSource (TriggerSourceEnum & value);
        VmbErrorType SetTriggerSource (TriggerSourceEnum value);
        VmbErrorType GetTriggerSourceFeature (AVT::VmbAPI::FeaturePtr & feature);


        // Category /AnalogControl
        VmbErrorType GetBlackLevel (double & value);
        VmbErrorType SetBlackLevel (double value);
        VmbErrorType GetBlackLevelFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetBlackLevelSelector (BlackLevelSelectorEnum & value);
        VmbErrorType SetBlackLevelSelector (BlackLevelSelectorEnum value);
        VmbErrorType GetBlackLevelSelectorFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGain (double & value);
        VmbErrorType SetGain (double value);
        VmbErrorType GetGainFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGainSelector (GainSelectorEnum & value);
        VmbErrorType SetGainSelector (GainSelectorEnum value);
        VmbErrorType GetGainSelectorFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetGamma (double & value);
        VmbErrorType SetGamma (double value);
        VmbErrorType GetGammaFeature (AVT::VmbAPI::FeaturePtr & feature);


        // Category /BufferHandlingControl
        VmbErrorType GetMaxDriverBuffersCount (VmbInt64_t & value);
        VmbErrorType SetMaxDriverBuffersCount (VmbInt64_t value);
        VmbErrorType GetMaxDriverBuffersCountFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetStreamAnnounceBufferMinimum (VmbInt64_t & value);
        VmbErrorType GetStreamAnnounceBufferMinimumFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetStreamAnnouncedBufferCount (VmbInt64_t & value);
        VmbErrorType GetStreamAnnouncedBufferCountFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetStreamBufferHandlingMode (StreamBufferHandlingModeEnum & value);
        VmbErrorType GetStreamBufferHandlingModeFeature (AVT::VmbAPI::FeaturePtr & feature);


        // Category /CorrectionControl
        VmbErrorType GetCorrectionMode (CorrectionModeEnum & value);
        VmbErrorType SetCorrectionMode (CorrectionModeEnum value);
        VmbErrorType GetCorrectionModeFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetCorrectionSelector (CorrectionSelectorEnum & value);
        VmbErrorType SetCorrectionSelector (CorrectionSelectorEnum value);
        VmbErrorType GetCorrectionSelectorFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetCorrectionSetDefault (CorrectionSetDefaultEnum & value);
        VmbErrorType SetCorrectionSetDefault (CorrectionSetDefaultEnum value);
        VmbErrorType GetCorrectionSetDefaultFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetCorrectionSetSelector (CorrectionSetSelectorEnum & value);
        VmbErrorType SetCorrectionSetSelector (CorrectionSetSelectorEnum value);
        VmbErrorType GetCorrectionSetSelectorFeature (AVT::VmbAPI::FeaturePtr & feature);


        // Category /CorrectionControl/CorrectionInfo
        VmbErrorType GetCorrectionDataSize (VmbInt64_t & value);
        VmbErrorType GetCorrectionDataSizeFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetCorrectionEntryType (VmbInt64_t & value);
        VmbErrorType GetCorrectionEntryTypeFeature (AVT::VmbAPI::FeaturePtr & feature);


        // Category /DeviceControl
        VmbErrorType GetDeviceFamilyName (std::string & value);
        VmbErrorType GetDeviceFamilyNameFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetDeviceFirmwareID (std::string & value);
        VmbErrorType GetDeviceFirmwareIDFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetDeviceFirmwareIDSelector (DeviceFirmwareIDSelectorEnum & value);
        VmbErrorType SetDeviceFirmwareIDSelector (DeviceFirmwareIDSelectorEnum value);
        VmbErrorType GetDeviceFirmwareIDSelectorFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetDeviceFirmwareVersion (std::string & value);
        VmbErrorType GetDeviceFirmwareVersionFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetDeviceFirmwareVersionSelector (DeviceFirmwareVersionSelectorEnum & value);
        VmbErrorType SetDeviceFirmwareVersionSelector (DeviceFirmwareVersionSelectorEnum value);
        VmbErrorType GetDeviceFirmwareVersionSelectorFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetDeviceGenCPVersionMajor (VmbInt64_t & value);
        VmbErrorType GetDeviceGenCPVersionMajorFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetDeviceGenCPVersionMinor (VmbInt64_t & value);
        VmbErrorType GetDeviceGenCPVersionMinorFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetDeviceIndicatorMode (DeviceIndicatorModeEnum & value);
        VmbErrorType SetDeviceIndicatorMode (DeviceIndicatorModeEnum value);
        VmbErrorType GetDeviceIndicatorModeFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetDeviceLinkThroughputLimit (VmbInt64_t & value);
        VmbErrorType SetDeviceLinkThroughputLimit (VmbInt64_t value);
        VmbErrorType GetDeviceLinkThroughputLimitFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetDeviceLinkThroughputLimitMode (DeviceLinkThroughputLimitModeEnum & value);
        VmbErrorType SetDeviceLinkThroughputLimitMode (DeviceLinkThroughputLimitModeEnum value);
        VmbErrorType GetDeviceLinkThroughputLimitModeFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetDeviceManufacturerInfo (std::string & value);
        VmbErrorType GetDeviceManufacturerInfoFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetDeviceModelName (std::string & value);
        VmbErrorType GetDeviceModelNameFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType DeviceReset ();
        VmbErrorType GetDeviceResetFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetDeviceSFNCVersionMajor (VmbInt64_t & value);
        VmbErrorType GetDeviceSFNCVersionMajorFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetDeviceSFNCVersionMinor (VmbInt64_t & value);
        VmbErrorType GetDeviceSFNCVersionMinorFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetDeviceSFNCVersionSubMinor (VmbInt64_t & value);
        VmbErrorType GetDeviceSFNCVersionSubMinorFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetDeviceScanType (DeviceScanTypeEnum & value);
        VmbErrorType GetDeviceScanTypeFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetDeviceSerialNumber (std::string & value);
        VmbErrorType GetDeviceSerialNumberFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetDeviceTemperature (double & value);
        VmbErrorType GetDeviceTemperatureFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetDeviceTemperatureSelector (DeviceTemperatureSelectorEnum & value);
        VmbErrorType SetDeviceTemperatureSelector (DeviceTemperatureSelectorEnum value);
        VmbErrorType GetDeviceTemperatureSelectorFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetDeviceUserID (std::string & value);
        VmbErrorType SetDeviceUserID (const char * value);
        VmbErrorType GetDeviceUserIDFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetDeviceVendorName (std::string & value);
        VmbErrorType GetDeviceVendorNameFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetDeviceVersion (std::string & value);
        VmbErrorType GetDeviceVersionFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetTimestamp (VmbInt64_t & value);
        VmbErrorType GetTimestampFeature (AVT::VmbAPI::FeaturePtr & feature);


        // Category /DigitalIOControl
        VmbErrorType GetInputDebounceMode (InputDebounceModeEnum & value);
        VmbErrorType SetInputDebounceMode (InputDebounceModeEnum value);
        VmbErrorType GetInputDebounceModeFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetInputDebounceTime (double & value);
        VmbErrorType SetInputDebounceTime (double value);
        VmbErrorType GetInputDebounceTimeFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetLineInverter (bool & value);
        VmbErrorType SetLineInverter (bool value);
        VmbErrorType GetLineInverterFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetLineMode (LineModeEnum & value);
        VmbErrorType SetLineMode (LineModeEnum value);
        VmbErrorType GetLineModeFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetLineSelector (LineSelectorEnum & value);
        VmbErrorType SetLineSelector (LineSelectorEnum value);
        VmbErrorType GetLineSelectorFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetLineSource (LineSourceEnum & value);
        VmbErrorType GetLineSourceFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetLineStatus (bool & value);
        VmbErrorType GetLineStatusFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetOutputDurationMode (OutputDurationModeEnum & value);
        VmbErrorType SetOutputDurationMode (OutputDurationModeEnum value);
        VmbErrorType GetOutputDurationModeFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetOutputDurationTime (double & value);
        VmbErrorType SetOutputDurationTime (double value);
        VmbErrorType GetOutputDurationTimeFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetUserOutputSelector (UserOutputSelectorEnum & value);
        VmbErrorType SetUserOutputSelector (UserOutputSelectorEnum value);
        VmbErrorType GetUserOutputSelectorFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetUserOutputValue (bool & value);
        VmbErrorType SetUserOutputValue (bool value);
        VmbErrorType GetUserOutputValueFeature (AVT::VmbAPI::FeaturePtr & feature);


        // Category /FileAccessControl
        VmbErrorType GetFileAccessBuffer (AVT::VmbAPI::UcharVector & value);
        VmbErrorType GetFileAccessBufferFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetFileAccessLength (VmbInt64_t & value);
        VmbErrorType GetFileAccessLengthFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetFileAccessOffset (VmbInt64_t & value);
        VmbErrorType GetFileAccessOffsetFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetFileOpenMode (FileOpenModeEnum & value);
        VmbErrorType SetFileOpenMode (FileOpenModeEnum value);
        VmbErrorType GetFileOpenModeFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType FileOperationExecute ();
        VmbErrorType GetFileOperationExecuteFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetFileOperationResult (VmbInt64_t & value);
        VmbErrorType GetFileOperationResultFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetFileOperationSelector (FileOperationSelectorEnum & value);
        VmbErrorType SetFileOperationSelector (FileOperationSelectorEnum value);
        VmbErrorType GetFileOperationSelectorFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetFileOperationStatus (FileOperationStatusEnum & value);
        VmbErrorType GetFileOperationStatusFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetFileProcessStatus (FileProcessStatusEnum & value);
        VmbErrorType GetFileProcessStatusFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetFileSelector (FileSelectorEnum & value);
        VmbErrorType SetFileSelector (FileSelectorEnum value);
        VmbErrorType GetFileSelectorFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetFileSize (VmbInt64_t & value);
        VmbErrorType GetFileSizeFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetFileStatus (FileStatusEnum & value);
        VmbErrorType GetFileStatusFeature (AVT::VmbAPI::FeaturePtr & feature);


        // Category /ImageFormatControl
        VmbErrorType GetHeight (VmbInt64_t & value);
        VmbErrorType SetHeight (VmbInt64_t value);
        VmbErrorType GetHeightFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetHeightMax (VmbInt64_t & value);
        VmbErrorType GetHeightMaxFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetOffsetX (VmbInt64_t & value);
        VmbErrorType SetOffsetX (VmbInt64_t value);
        VmbErrorType GetOffsetXFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetOffsetY (VmbInt64_t & value);
        VmbErrorType SetOffsetY (VmbInt64_t value);
        VmbErrorType GetOffsetYFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetPixelFormat (PixelFormatEnum & value);
        VmbErrorType SetPixelFormat (PixelFormatEnum value);
        VmbErrorType GetPixelFormatFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetPixelSize (PixelSizeEnum & value);
        VmbErrorType GetPixelSizeFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetReverseX (bool & value);
        VmbErrorType SetReverseX (bool value);
        VmbErrorType GetReverseXFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetSensorHeight (VmbInt64_t & value);
        VmbErrorType GetSensorHeightFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetSensorWidth (VmbInt64_t & value);
        VmbErrorType GetSensorWidthFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetWidth (VmbInt64_t & value);
        VmbErrorType SetWidth (VmbInt64_t value);
        VmbErrorType GetWidthFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetWidthMax (VmbInt64_t & value);
        VmbErrorType GetWidthMaxFeature (AVT::VmbAPI::FeaturePtr & feature);


        // Category /StreamInformation
        VmbErrorType GetStreamID (std::string & value);
        VmbErrorType GetStreamIDFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetStreamIsGrabbing (bool & value);
        VmbErrorType GetStreamIsGrabbingFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetStreamType (StreamTypeEnum & value);
        VmbErrorType GetStreamTypeFeature (AVT::VmbAPI::FeaturePtr & feature);


        // Category /TestControl
        VmbErrorType GetTestPendingAck (VmbInt64_t & value);
        VmbErrorType SetTestPendingAck (VmbInt64_t value);
        VmbErrorType GetTestPendingAckFeature (AVT::VmbAPI::FeaturePtr & feature);


        // Category /TransportLayerControl
        VmbErrorType GetPayloadSize (VmbInt64_t & value);
        VmbErrorType GetPayloadSizeFeature (AVT::VmbAPI::FeaturePtr & feature);


        // Category /UserSetControl
        VmbErrorType GetUserSetDefault (UserSetDefaultEnum & value);
        VmbErrorType SetUserSetDefault (UserSetDefaultEnum value);
        VmbErrorType GetUserSetDefaultFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType UserSetLoad ();
        VmbErrorType GetUserSetLoadFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType UserSetSave ();
        VmbErrorType GetUserSetSaveFeature (AVT::VmbAPI::FeaturePtr & feature);

        VmbErrorType GetUserSetSelector (UserSetSelectorEnum & value);
        VmbErrorType SetUserSetSelector (UserSetSelectorEnum value);
        VmbErrorType GetUserSetSelectorFeature (AVT::VmbAPI::FeaturePtr & feature);


    private:
        AVT::VmbAPI::FeaturePtr m_AcquisitionAbortFeature;
        AVT::VmbAPI::FeaturePtr m_AcquisitionFrameCountFeature;
        AVT::VmbAPI::FeaturePtr m_AcquisitionFrameRateFeature;
        AVT::VmbAPI::FeaturePtr m_AcquisitionFrameRateModeFeature;
        AVT::VmbAPI::FeaturePtr m_AcquisitionModeFeature;
        AVT::VmbAPI::FeaturePtr m_AcquisitionStartFeature;
        AVT::VmbAPI::FeaturePtr m_AcquisitionStatusFeature;
        AVT::VmbAPI::FeaturePtr m_AcquisitionStatusSelectorFeature;
        AVT::VmbAPI::FeaturePtr m_AcquisitionStopFeature;
        AVT::VmbAPI::FeaturePtr m_ExposureModeFeature;
        AVT::VmbAPI::FeaturePtr m_ExposureTimeFeature;
        AVT::VmbAPI::FeaturePtr m_TriggerActivationFeature;
        AVT::VmbAPI::FeaturePtr m_TriggerDelayFeature;
        AVT::VmbAPI::FeaturePtr m_TriggerModeFeature;
        AVT::VmbAPI::FeaturePtr m_TriggerSelectorFeature;
        AVT::VmbAPI::FeaturePtr m_TriggerSoftwareFeature;
        AVT::VmbAPI::FeaturePtr m_TriggerSourceFeature;
        AVT::VmbAPI::FeaturePtr m_BlackLevelFeature;
        AVT::VmbAPI::FeaturePtr m_BlackLevelSelectorFeature;
        AVT::VmbAPI::FeaturePtr m_GainFeature;
        AVT::VmbAPI::FeaturePtr m_GainSelectorFeature;
        AVT::VmbAPI::FeaturePtr m_GammaFeature;
        AVT::VmbAPI::FeaturePtr m_MaxDriverBuffersCountFeature;
        AVT::VmbAPI::FeaturePtr m_StreamAnnounceBufferMinimumFeature;
        AVT::VmbAPI::FeaturePtr m_StreamAnnouncedBufferCountFeature;
        AVT::VmbAPI::FeaturePtr m_StreamBufferHandlingModeFeature;
        AVT::VmbAPI::FeaturePtr m_CorrectionModeFeature;
        AVT::VmbAPI::FeaturePtr m_CorrectionSelectorFeature;
        AVT::VmbAPI::FeaturePtr m_CorrectionSetDefaultFeature;
        AVT::VmbAPI::FeaturePtr m_CorrectionSetSelectorFeature;
        AVT::VmbAPI::FeaturePtr m_CorrectionDataSizeFeature;
        AVT::VmbAPI::FeaturePtr m_CorrectionEntryTypeFeature;
        AVT::VmbAPI::FeaturePtr m_DeviceFamilyNameFeature;
        AVT::VmbAPI::FeaturePtr m_DeviceFirmwareIDFeature;
        AVT::VmbAPI::FeaturePtr m_DeviceFirmwareIDSelectorFeature;
        AVT::VmbAPI::FeaturePtr m_DeviceFirmwareVersionFeature;
        AVT::VmbAPI::FeaturePtr m_DeviceFirmwareVersionSelectorFeature;
        AVT::VmbAPI::FeaturePtr m_DeviceGenCPVersionMajorFeature;
        AVT::VmbAPI::FeaturePtr m_DeviceGenCPVersionMinorFeature;
        AVT::VmbAPI::FeaturePtr m_DeviceIndicatorModeFeature;
        AVT::VmbAPI::FeaturePtr m_DeviceLinkThroughputLimitFeature;
        AVT::VmbAPI::FeaturePtr m_DeviceLinkThroughputLimitModeFeature;
        AVT::VmbAPI::FeaturePtr m_DeviceManufacturerInfoFeature;
        AVT::VmbAPI::FeaturePtr m_DeviceModelNameFeature;
        AVT::VmbAPI::FeaturePtr m_DeviceResetFeature;
        AVT::VmbAPI::FeaturePtr m_DeviceSFNCVersionMajorFeature;
        AVT::VmbAPI::FeaturePtr m_DeviceSFNCVersionMinorFeature;
        AVT::VmbAPI::FeaturePtr m_DeviceSFNCVersionSubMinorFeature;
        AVT::VmbAPI::FeaturePtr m_DeviceScanTypeFeature;
        AVT::VmbAPI::FeaturePtr m_DeviceSerialNumberFeature;
        AVT::VmbAPI::FeaturePtr m_DeviceTemperatureFeature;
        AVT::VmbAPI::FeaturePtr m_DeviceTemperatureSelectorFeature;
        AVT::VmbAPI::FeaturePtr m_DeviceUserIDFeature;
        AVT::VmbAPI::FeaturePtr m_DeviceVendorNameFeature;
        AVT::VmbAPI::FeaturePtr m_DeviceVersionFeature;
        AVT::VmbAPI::FeaturePtr m_TimestampFeature;
        AVT::VmbAPI::FeaturePtr m_InputDebounceModeFeature;
        AVT::VmbAPI::FeaturePtr m_InputDebounceTimeFeature;
        AVT::VmbAPI::FeaturePtr m_LineInverterFeature;
        AVT::VmbAPI::FeaturePtr m_LineModeFeature;
        AVT::VmbAPI::FeaturePtr m_LineSelectorFeature;
        AVT::VmbAPI::FeaturePtr m_LineSourceFeature;
        AVT::VmbAPI::FeaturePtr m_LineStatusFeature;
        AVT::VmbAPI::FeaturePtr m_OutputDurationModeFeature;
        AVT::VmbAPI::FeaturePtr m_OutputDurationTimeFeature;
        AVT::VmbAPI::FeaturePtr m_UserOutputSelectorFeature;
        AVT::VmbAPI::FeaturePtr m_UserOutputValueFeature;
        AVT::VmbAPI::FeaturePtr m_FileAccessBufferFeature;
        AVT::VmbAPI::FeaturePtr m_FileAccessLengthFeature;
        AVT::VmbAPI::FeaturePtr m_FileAccessOffsetFeature;
        AVT::VmbAPI::FeaturePtr m_FileOpenModeFeature;
        AVT::VmbAPI::FeaturePtr m_FileOperationExecuteFeature;
        AVT::VmbAPI::FeaturePtr m_FileOperationResultFeature;
        AVT::VmbAPI::FeaturePtr m_FileOperationSelectorFeature;
        AVT::VmbAPI::FeaturePtr m_FileOperationStatusFeature;
        AVT::VmbAPI::FeaturePtr m_FileProcessStatusFeature;
        AVT::VmbAPI::FeaturePtr m_FileSelectorFeature;
        AVT::VmbAPI::FeaturePtr m_FileSizeFeature;
        AVT::VmbAPI::FeaturePtr m_FileStatusFeature;
        AVT::VmbAPI::FeaturePtr m_HeightFeature;
        AVT::VmbAPI::FeaturePtr m_HeightMaxFeature;
        AVT::VmbAPI::FeaturePtr m_OffsetXFeature;
        AVT::VmbAPI::FeaturePtr m_OffsetYFeature;
        AVT::VmbAPI::FeaturePtr m_PixelFormatFeature;
        AVT::VmbAPI::FeaturePtr m_PixelSizeFeature;
        AVT::VmbAPI::FeaturePtr m_ReverseXFeature;
        AVT::VmbAPI::FeaturePtr m_SensorHeightFeature;
        AVT::VmbAPI::FeaturePtr m_SensorWidthFeature;
        AVT::VmbAPI::FeaturePtr m_WidthFeature;
        AVT::VmbAPI::FeaturePtr m_WidthMaxFeature;
        AVT::VmbAPI::FeaturePtr m_StreamIDFeature;
        AVT::VmbAPI::FeaturePtr m_StreamIsGrabbingFeature;
        AVT::VmbAPI::FeaturePtr m_StreamTypeFeature;
        AVT::VmbAPI::FeaturePtr m_TestPendingAckFeature;
        AVT::VmbAPI::FeaturePtr m_PayloadSizeFeature;
        AVT::VmbAPI::FeaturePtr m_UserSetDefaultFeature;
        AVT::VmbAPI::FeaturePtr m_UserSetLoadFeature;
        AVT::VmbAPI::FeaturePtr m_UserSetSaveFeature;
        AVT::VmbAPI::FeaturePtr m_UserSetSelectorFeature;
};

#endif
